### ISSUE TITLE
Erro 404 when do click in the confirm email

### ISSUE THREAD

**Issue by gonzalesc** [Newsman/newsman-api-php#1]
Hi.
I use initSubscribe() to subscribe my customers and it works but when it send email to confirm to client and he do click to link.

![image](https://user-images.githubusercontent.com/2523478/55383643-18254480-54ff-11e9-8b9e-14e3e359bc1d.png)

After, when client do click, it show error 404.
![image](https://user-images.githubusercontent.com/2523478/55383693-33904f80-54ff-11e9-882c-99c4821b8e97.png)

Regards

**Comment by dazoot** [comment]
It seems the redirect to your site does 404 (after you click the Continue button), because the site link does not include http:// or https:// (you can update your site URL in the list settings).
